import 'jquery/dist/jquery'
import 'bootstrap/dist/css/bootstrap.css'
import 'blueimp-file-upload/css/jquery.fileupload.css'
import 'jquery.ui.widget/jquery.ui.widget'
import 'blueimp-load-image'
import 'blueimp-file-upload'
import 'blueimp-file-upload/js/jquery.fileupload-image.js'
import 'blueimp-load-image/js/load-image-scale.js'
import 'blueimp-load-image/js/load-image-meta.js'
import 'blueimp-load-image/js/load-image-exif.js'
// import 'bootstrap/dist/css/bootstrap-theme.css'
// import 'bootstrap/dist/js/bootstrap'
// import '../styles.scss'
import {APP} from '../deps.js'
import '../styles.scss'
import '../folders.js'
import '../image_upload/image_upload.js'
import '../image_upload/image_upload.scss'
import '../scanlet/projects.scss'
import '../scanlet/groups.scss'

console.log(APP)
